# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Grotewold Lab
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Michigan State University, 
  College of Natural Science, 
  Biochemistry and Molecular Biology
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "nicolas-van/bootstrap-4-github-pages"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap


# Load md files in _publications folder
# used in publications.md
collections:
  publications:
    sort_by: path


# navigation bar with dropdowns
navigation:
    - title: Projects
      url: /projects
      subpages:
        - title: Gene Regulation
          url: /projects#project1
        - title: Phenolic Compounds
          url: /projects#project2
        - title: Flavone Pathways
          url: /projects#project3
        - title: Seed Oils
          url: /projects#project4
          
          
    - title: Databases
      url: /databases
      subpages:
        - title: Agris
          url: /databases#agris
        - title: GRASSIUS
          url: /databases#grassius
        - title: CamRegBase
          url: /databases#camregbase

    - title: Information
      url: /
      subpages:
        - title: News
          url: /news
        - title: Publications
          url: /publications
        - title: Resources
          url: /resources

    - title: People
      url: /people
      subpages:
        - title: Current Members
          url: /people
        - title: Previous Members
          url: /pastpeople
          
  
# list of lab members to appear on "People" page
# (should be a subset of the files in people folder)
current_members:
  - people/elliot-braun.md
  - people/emily-pawlowski.md
  - people/lina-gomez-cano.md
  - people/ronnie-dewberry.md
  - people/solo-mercene.md
  - people/tatiana-garcia.md
  
current_undergrads:

  
former_members:
  - people/sunnie-lee.md
  - people/suresh-gupta.md
  - people/oliver-tessmer.md
  - people/hannah-vandeweert.md
  - people/juan-de-los-campos.md
  - people/yi-hsuan-chu.md
  - people/brian-le.md
  - people/andre-wyzykowski.md
  - people/aytug-ulutas.md
  - people/luke-benedict.md
  - people/lily-moura.md
  - people/liz-christensen.md
  - people/rigo-santiago.md
  - people/fabio-gomez-cano.md
  - people/mariel-cruz-gomez.md
  - people/nan-jiang.md
  - people/julieta-petrich.md
  - people/avery-hickcox.md
  - people/nevaeh-marshall.md
  - people/radin-sadre.md
  - people/sara-hasegawa.md
  - people/beth-shackleford.md
  - people/julia-matalon.md
  - people/meadow-maturen.md
  - people/chris-infante.md
  - people/hesham-abdullah.md
  - people/rajneesh-singhal.md
  - people/allison-barbaglia-hurlock.md
  - people/audrey-tacderas.md
  - people/eric-mukundi-maina.md
  - people/hadi-nayebi-gavgani.md
  - people/kengo-morohashi.md
  - people/megha-singhal.md
  - people/shannon-schrope.md
  - people/spencer-kuehn.md
  - people/yabdiel-olmeda-santiago.md
  


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
